"""market_value_score

Revision ID: e6cfe27d10c6
Revises: 0002_create_tables
Create Date: 2026-07-21 11:34:58.372584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0003_market_value_score"
down_revision = "0002_create_tables"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_market_value_score',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('performance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('potential_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reputation_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('league_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('availability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mvs_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['staging.player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'as_of_date', name='uq_player_market_value_score'),
    schema='features'
    )
    op.create_table('player_style_profile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('position_bucket', postgresql.ENUM('Goalkeeper', 'Defender', 'Midfielder', 'Attacker', name='position_bucket', schema='staging'), nullable=False),
    sa.Column('cluster_id', sa.SmallInteger(), nullable=True),
    sa.Column('cluster_label', sa.Text(), nullable=True),
    sa.Column('matches_in_window', sa.SmallInteger(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['staging.player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'as_of_date', name='uq_player_style_profile'),
    schema='features'
    )
    op.create_table('api_football_fixture_detail',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['raw.source_ingestion_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('api_football_injuries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['raw.source_ingestion_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('understat_player_match',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['raw.source_ingestion_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('player_injury',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('injury_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['staging.player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('player_match_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('minutes', sa.SmallInteger(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('position_bucket', postgresql.ENUM('Goalkeeper', 'Defender', 'Midfielder', 'Attacker', name='position_bucket', schema='staging'), nullable=True),
    sa.Column('goals', sa.SmallInteger(), nullable=True),
    sa.Column('assists', sa.SmallInteger(), nullable=True),
    sa.Column('shots', sa.SmallInteger(), nullable=True),
    sa.Column('shots_on_target', sa.SmallInteger(), nullable=True),
    sa.Column('key_passes', sa.SmallInteger(), nullable=True),
    sa.Column('pass_accuracy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tackles', sa.SmallInteger(), nullable=True),
    sa.Column('interceptions', sa.SmallInteger(), nullable=True),
    sa.Column('duels_total', sa.SmallInteger(), nullable=True),
    sa.Column('duels_won', sa.SmallInteger(), nullable=True),
    sa.Column('dribbles_attempts', sa.SmallInteger(), nullable=True),
    sa.Column('dribbles_success', sa.SmallInteger(), nullable=True),
    sa.Column('dribbled_past', sa.SmallInteger(), nullable=True),
    sa.Column('fouls_drawn', sa.SmallInteger(), nullable=True),
    sa.Column('fouls_committed', sa.SmallInteger(), nullable=True),
    sa.Column('yellow_cards', sa.SmallInteger(), nullable=True),
    sa.Column('red_cards', sa.SmallInteger(), nullable=True),
    sa.Column('xg', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('xa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('npxg', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['staging.match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['staging.player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['staging.team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_player_match_stats'),
    schema='staging'
    )
    op.drop_table('transfermarkt_lineup', schema='raw')
    op.drop_table('player_valuation', schema='staging')
    op.drop_table('transfermarkt_valuation', schema='raw')
    op.alter_column('team_match_features', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='features')
    op.drop_column('team_match_features', 'squad_valuation_eur', schema='features')
    op.alter_column('football_data_match', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='raw')
    op.alter_column('source_ingestion_log', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='raw')
    op.alter_column('understat_match_stats', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='raw')
    op.alter_column('competition', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('lineup', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('match', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('player', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('team', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('team_match', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_match', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('team', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('player', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('match', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('lineup', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('competition', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='staging')
    op.alter_column('understat_match_stats', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='raw')
    op.alter_column('source_ingestion_log', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='raw')
    op.alter_column('football_data_match', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='raw')
    op.add_column('team_match_features', sa.Column('squad_valuation_eur', sa.BIGINT(), autoincrement=False, nullable=True), schema='features')
    op.alter_column('team_match_features', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='features')
    op.create_table('transfermarkt_valuation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ingestion_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingestion_id'], ['raw.source_ingestion_log.id'], name=op.f('transfermarkt_valuation_ingestion_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transfermarkt_valuation_pkey')),
    schema='raw'
    )
    op.create_table('player_valuation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('value_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('value_eur', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['staging.player.id'], name=op.f('player_valuation_player_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('player_valuation_pkey')),
    sa.UniqueConstraint('player_id', 'value_date', name=op.f('uq_player_valuation'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='staging'
    )
    op.create_table('transfermarkt_lineup',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ingestion_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingestion_id'], ['raw.source_ingestion_log.id'], name=op.f('transfermarkt_lineup_ingestion_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transfermarkt_lineup_pkey')),
    schema='raw'
    )
    op.drop_table('player_match_stats', schema='staging')
    op.drop_table('player_injury', schema='staging')
    op.drop_table('understat_player_match', schema='raw')
    op.drop_table('api_football_injuries', schema='raw')
    op.drop_table('api_football_fixture_detail', schema='raw')
    op.drop_table('player_style_profile', schema='features')
    op.drop_table('player_market_value_score', schema='features')
    # ### end Alembic commands ###
